name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar toolchain C (gcc, make)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Garantir permissão de execução dos testes
        run: |
          if [ -d testes ]; then
            chmod +x testes/*.sh || true
          fi

      - name: Compilar
        run: make -j$(nproc)

      - name: Rodar testes
        run: make test
